server:
  port: 8082

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/dbtest
      username: root
      password: wjdehddnr1@
      minimum-idle: 5
      maximum-pool-size: 5

  data:
    redis:
      port: 6379
      host: localhost
      password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect