server:
  port: 8082

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/dbtest
      username: root
      password: wjdehddnr1@
      minimum-idle: 10
      maximum-pool-size: 10

  data:
    redis:
#      port: 27017
#      host: 192.168.10.44
#      password: 1004
      port: 6379
      host: localhost
      password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect